config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root "static_pages#home"

  resources :users do
    resources :jobs, controller: "user/jobs"
    resources :applications, controller: "user/applications"
  end
end

app/models/application.rb
class Application < ApplicationRecord
  validates :user, uniqueness: true

  belongs_to :user
  belongs_to :job
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer.rb
class Employer < User
  has_many :jobs
  accepts_nested_attributes_for :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employer, required: false, class_name: "User"
  has_many :applications
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :applications

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      if current_user.class == Employer
        @jobs = Job.where(employer_id: current_user.id).joins(:applications).distinct
      else
        @jobs = Job.left_outer_joins(:applications).where("applications.user_id != ?", current_user.id)
        @jobs_applied = Job.joins(:applications).where(applications: {user_id: current_user.id})
      end
    end
  end
end

app/controllers/user/applications_controller.rb
class User::ApplicationsController < ApplicationController
  def create
    if current_user.applications.create(job_id: params[:job_id])
      flash[:success] = "Job successfully applied to"
    else
      flash[:alert] = "Error occurred"
    end
    redirect_to root_path
  end
end

app/controllers/user/jobs_controller.rb
class User::JobsController < ApplicationController
  before_action :load_user
  def create
    if @user.jobs.create(job_params)
      flash[:success] = "Job created successfully"
      redirect_to root_path
    else
      flash[:alert] = "Error Occurred"
      redirect_to root_path
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :description)
  end

  def load_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  def sign_up_params
    params.require(:user).permit(:type, :email, :password, :password_confirmation)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user/applications_helper.rb
module User::ApplicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.haml
%h1.text-center Job Board I Hate Homework
-if current_user
  %h2 Current User
  %p= "ID: #{current_user.id}"
  %p= "Type: #{current_user.class}"
  %p= "Email: #{current_user.email}"
  %br

- if user_signed_in?
  - if current_user.class == Employer

    %h2 Jobs With Applications
    - @jobs.each do |j|
      .row
        .col-3
          %p= "<strong>Name:</strong> #{j.title}".html_safe
        .col-3
          %p= "<strong>Title:</strong> #{j.description}".html_safe
    %br

    %h2 Create Jobs
    = flash[:success]
    = flash[:alert]
    = form_for :job, url: user_jobs_path(current_user), method: :post do |f|
      = f.label :title
      %br
      = f.text_field :title
      %br
      %br
      = f.label :description
      %br
      = f.text_field :description
      %br

      = f.submit "Create job Post", class: "btn btn-primary"

    = link_to "Sign Out", destroy_user_session_path, method: :delete

  - else
    %h2 Jobs Available
    - @jobs.each do |j|
      .row
        .col-4
          %p= "<strong>Employer Name:</strong> #{j.employer.name}".html_safe
        .col-3
          %p= "<strong>Company:</strong> #{j.title}".html_safe
        .col-3
          %p= "<strong>Title:</strong> #{j.description}".html_safe
        .col-2
          = link_to "Apply", user_applications_path(current_user, {job_id: j.id}), class: "btn btn-primary", method: :post

    %h2 Jobs I Applied To
    - @jobs_applied.each do |j|
      .row
        .col-3
          %p= "<strong>Name:</strong> #{j.title}".html_safe

    = link_to "Sign Out", destroy_user_session_path, method: :delete

- else
  %h2 Log in

  = form_for :user, url: new_session_path(:user) do |f|
    .field
      = f.label :email
      %br
      = f.email_field :email, autofocus: true, autocomplete: "email"

    .field
      = f.label :password
      %br
      = f.password_field :password, autocomplete: "current-password"

    .actions
      = f.submit "Log in"

  = render "devise/shared/links"